# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsyX93dzRyGVXD9Oxhmb07K60CwWFJQ0
"""

#Loan Approved prediction

import pandas as pd
df=pd.read_csv("/content/loanapproval.csv")
df

#check null value
df.isnull().sum()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["employment_status"]=le.fit_transform(df["employment_status"])
df["gender"]=le.fit_transform(df["gender"])
df["marital_status"]=le.fit_transform(df["marital_status"])
df

x=df.drop("loan_approved",axis=1)
y=df["loan_approved"]
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=500)
lr.fit(x_train,y_train)

y_pred  = lr.predict(x_test)
y_pred

le.classes_

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

y_pred  = lr.predict(x_test)
y_pred

y_test

from sklearn.metrics import classification_report
classification_report(y_test,y_pred)